=== masc3d/material-sheet-fab/leoz-node-data/src/main/resources/db/node/tables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tables" type="w3s:tablesType" xmlns:w3s="http://www.w3schools.com">
    <xs:annotation>
      <xs:documentation>Table mapping names to @Serialzable uids.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="tableType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="uid" use="required"/>
        <xs:attribute type="xs:string" name="pkuid" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="tablesType">
    <xs:sequence>
      <xs:element type="w3s:tableType" name="table" maxOccurs="unbounded" minOccurs="0" xmlns:w3s="http://www.w3schools.com"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== masc3d/material-sheet-fab/leoz-node/src/main/resources/db/tables.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!-- Table mapping names to @Serialzable uids. -->
<tables xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3schools.com tables.xsd">

    <table name="mst_bundle_version" uid="0x6a0acd69ac1a6c" />
    <table name="mst_country" uid="0x61175aa6b510b3" />
    <table name="mst_holiday_ctrl" uid="0x56c4d6ff7b69dc" pkuid="0x0bef5f538e4ed9" />
    <table name="mst_route" uid="0xef6d8232d3263d" />
    <table name="mst_routing_layer" uid="0x92ed6a2fc3f79f" />
    <table name="mst_sector" uid="0xf1dec2bb66db87" pkuid="0xd432b301532a4a" />
    <table name="mst_station" uid="0x1f6229f711c472" />
    <table name="mst_station_sector" uid="0x0d1eaebfd81899" pkuid="0x4a81cc447bdc43" />
    <table name="sys_property" uid="0xaa946790064006" pkuid="0x72b4356618387dL" />
</tables>

=== masc3d/material-sheet-fab/leoz-node-data/src/main/resources/db/node/tables.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!-- Table mapping names to @Serialzable uids. -->
<tables xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3schools.com tables.xsd">

    <table name="mst_bundle_version" uid="0x6a0acd69ac1a6c" />
    <table name="mst_country" uid="0x61175aa6b510b3" />
    <table name="mst_holiday_ctrl" uid="0x56c4d6ff7b69dc" />
    <table name="mst_node" uid="0xee9824a64c632c" />
    <table name="mst_route" uid="0xef6d8232d3263d" />
    <table name="mst_routing_layer" uid="0x92ed6a2fc3f79f" />
    <table name="mst_sector" uid="0xf1dec2bb66db87" />
    <table name="mst_station" uid="0x1f6229f711c472" />
    <table name="mst_station_sector" uid="0x0d1eaebfd81899" />
    <table name="lcl_property" uid="0xaa946790064006" />
    <table name="lcl_sync" uid="0x2244b44d5f16ff" />
    <table name="tad_node_geoposition" uid="0xaa946790064007" />
    <table name="tad_tour" uid="0x08b6aa2cdefbb2" />
    <table name="tad_tour_entry" uid="0x6c32a669a4a424" />
    <table name="mst_debitor_station" uid="0xaa946790064008" />
    <table name="mst_debitor" uid="0xaa946790064009" />
    <table name="mst_key" uid="0x8556806322cf47" />
    <table name="mst_user" uid="0xd0345b4eedac00" />
    <table name="mst_station_user" uid="0xea2337d04d0a2b" />
    <table name="tad_order" uid="0x9a5068e155ba00" />
    <table name="tad_order_parcel" uid="0x08cfee2e2d5075" />
</tables>
